module dice_cgra_subs
  import dice_pkg::*;
(
    input  logic clk_i,
    input  logic reset_i,
    input  logic en_i,

    input  logic [DICE_MEM_DATA_WIDTH-1:0] cm0_data_i,
    input  logic [((DICE_BITSTREAM_SIZE + DICE_MEM_DATA_WIDTH - 1)
                    / DICE_MEM_DATA_WIDTH)-1:0] cm0_chunk_en_i,
    input  logic [DICE_MEM_DATA_WIDTH-1:0] cm1_data_i,
    input  logic [((DICE_BITSTREAM_SIZE + DICE_MEM_DATA_WIDTH - 1)
                    / DICE_MEM_DATA_WIDTH)-1:0] cm1_chunk_en_i,

    input  logic v_i,
    input  logic bank_i,
    output logic ready_o,
    output logic busy_o,
    output logic [1:0] bank_valid_o,
    output logic prog_dout_o,
    output logic prog_we_o,

    input  logic [15:0] ext_data_i_0,
    input  logic [15:0] ext_data_i_1,
    input  logic [15:0] ext_data_i_2,
    input  logic [15:0] ext_data_i_3,
    input  logic [15:0] ext_data_i_4,
    input  logic [15:0] ext_data_i_5,
    input  logic [15:0] ext_data_i_6,
    input  logic [15:0] ext_data_i_7,
    input  logic [15:0] ext_data_i_8,
    input  logic [15:0] ext_data_i_9,
    input  logic [15:0] ext_data_i_10,
    input  logic [15:0] ext_data_i_11,
    input  logic [15:0] ext_data_i_12,
    input  logic [15:0] ext_data_i_13,
    input  logic [15:0] ext_data_i_14,
    input  logic [15:0] ext_data_i_15,
    output logic [15:0] ext_data_o_0,
    output logic [15:0] ext_data_o_1,
    output logic [15:0] ext_data_o_2,
    output logic [15:0] ext_data_o_3,
    output logic [15:0] ext_data_o_4,
    output logic [15:0] ext_data_o_5,
    output logic [15:0] ext_data_o_6,
    output logic [15:0] ext_data_o_7,
    output logic [15:0] ext_data_o_8,
    output logic [15:0] ext_data_o_9,
    output logic [15:0] ext_data_o_10,
    output logic [15:0] ext_data_o_11,
    output logic [15:0] ext_data_o_12,
    output logic [15:0] ext_data_o_13,
    output logic [15:0] ext_data_o_14,
    output logic [15:0] ext_data_o_15,

    input  logic ext_pred_i_0,
    input  logic ext_pred_i_1,
    output logic ext_pred_o_0,
    output logic ext_pred_o_1,

    output logic [15:0] mem_data_o,
    output logic [15:0] mem_addr_o
  );

  logic prog_rst_li;
  logic prog_done_li;
  logic prog_we_li;
  logic prog_din_li;
  cgra_bitstream_buf_serial bitstream_buf_serial_inst (
      .clk_i(clk_i),
      .reset_i(reset_i),
      .cm0_data_i(cm0_data_i),
      .cm0_chunk_en_i(cm0_chunk_en_i),
      .cm1_data_i(cm1_data_i),
      .cm1_chunk_en_i(cm1_chunk_en_i),
      .v_i(v_i),
      .bank_i(bank_i),
      .ready_o(ready_o),
      .busy_o(busy_o),
      .bank_valid_o(bank_valid_o),
      .prog_rst_o(prog_rst_li),
      .prog_done_o(prog_done_li),
      .prog_we_o(prog_we_li),
      .prog_din_o(prog_din_li)
  );

  dice_top cgra_inst (
      .clk_i(clk_i),
      .reset_i(reset_i),
      .en_i(en_i),
      .ext_data_i_0(ext_data_i_0),
      .ext_data_i_1(ext_data_i_1),
      .ext_data_i_2(ext_data_i_2),
      .ext_data_i_3(ext_data_i_3),
      .ext_data_i_4(ext_data_i_4),
      .ext_data_i_5(ext_data_i_5),
      .ext_data_i_6(ext_data_i_6),
      .ext_data_i_7(ext_data_i_7),
      .ext_data_i_8(ext_data_i_8),
      .ext_data_i_9(ext_data_i_9),
      .ext_data_i_10(ext_data_i_10),
      .ext_data_i_11(ext_data_i_11),
      .ext_data_i_12(ext_data_i_12),
      .ext_data_i_13(ext_data_i_13),
      .ext_data_i_14(ext_data_i_14),
      .ext_data_i_15(ext_data_i_15),
      .ext_data_o_0(ext_data_o_0),
      .ext_data_o_1(ext_data_o_1),
      .ext_data_o_2(ext_data_o_2),
      .ext_data_o_3(ext_data_o_3),
      .ext_data_o_4(ext_data_o_4),
      .ext_data_o_5(ext_data_o_5),
      .ext_data_o_6(ext_data_o_6),
      .ext_data_o_7(ext_data_o_7),
      .ext_data_o_8(ext_data_o_8),
      .ext_data_o_9(ext_data_o_9),
      .ext_data_o_10(ext_data_o_10),
      .ext_data_o_11(ext_data_o_11),
      .ext_data_o_12(ext_data_o_12),
      .ext_data_o_13(ext_data_o_13),
      .ext_data_o_14(ext_data_o_14),
      .ext_data_o_15(ext_data_o_15),
      .ext_pred_i_0(ext_pred_i_0),
      .ext_pred_i_1(ext_pred_i_1),
      .ext_pred_o_0(ext_pred_o_0),
      .ext_pred_o_1(ext_pred_o_1),
      .mem_data_o(mem_data_o),
      .mem_addr_o(mem_addr_o),
      .prog_clk_i(clk_i),
      .prog_rst_i(prog_rst_li),
      .prog_done_i(prog_done_li),
      .prog_we_i(prog_we_li),
      .prog_din_i(prog_din_li),
      .prog_dout_o(prog_dout_o),
      .prog_we_o(prog_we_o)
  );

endmodule
