// SystemVerilog auto-generated by DORA RTL generator
// Copyright (c) 2025, Pᴺ Computer Engineering Lab.

// Generated on: 2026-03-16 13:48:55.475073
// Author: jami3jun

module dice_top (
    // Ports
    input  logic clk_i,
    input  logic reset_i,
    input  logic en_i,
    input  logic [7:0] ext_data_i_0,
    input  logic [7:0] ext_data_i_1,
    input  logic [7:0] ext_data_i_2,
    input  logic [7:0] ext_data_i_3,
    input  logic [7:0] ext_data_i_4,
    input  logic [7:0] ext_data_i_5,
    input  logic [7:0] ext_data_i_6,
    input  logic [7:0] ext_data_i_7,
    input  logic [7:0] ext_data_i_8,
    input  logic [7:0] ext_data_i_9,
    input  logic [7:0] ext_data_i_10,
    input  logic [7:0] ext_data_i_11,
    input  logic [7:0] ext_data_i_12,
    input  logic [7:0] ext_data_i_13,
    input  logic [7:0] ext_data_i_14,
    input  logic [7:0] ext_data_i_15,
    output logic [7:0] ext_data_o_0,
    output logic [7:0] ext_data_o_1,
    output logic [7:0] ext_data_o_2,
    output logic [7:0] ext_data_o_3,
    output logic [7:0] ext_data_o_4,
    output logic [7:0] ext_data_o_5,
    output logic [7:0] ext_data_o_6,
    output logic [7:0] ext_data_o_7,
    output logic [7:0] ext_data_o_8,
    output logic [7:0] ext_data_o_9,
    output logic [7:0] ext_data_o_10,
    output logic [7:0] ext_data_o_11,
    output logic [7:0] ext_data_o_12,
    output logic [7:0] ext_data_o_13,
    output logic [7:0] ext_data_o_14,
    output logic [7:0] ext_data_o_15,
    input  logic ext_pred_i_0,
    input  logic ext_pred_i_1,
    output logic ext_pred_o_0,
    output logic ext_pred_o_1,
    output logic [7:0] mem_data_o,
    output logic [7:0] mem_addr_o,
    input  logic prog_clk_i,
    input  logic prog_rst_i,
    input  logic prog_done_i,
    input  logic prog_we_i,
    input  logic prog_din_i,
    output logic prog_dout_o,
    output logic prog_we_o
);
    logic [7:0] dice_array_sb_0_0_N_o;
    logic dice_array_sb_0_0_pred_N_o;
    logic [7:0] dice_array_sb_0_0_W_o;
    logic dice_array_sb_0_0_pred_W_o;
    logic [7:0] dice_array_sb_0_0_NE_o;
    logic dice_array_sb_0_0_pred_NE_o;
    logic [7:0] dice_array_sb_0_0_NW_o;
    logic dice_array_sb_0_0_pred_NW_o;
    logic [7:0] dice_array_sb_0_0_SW_o;
    logic dice_array_sb_0_0_pred_SW_o;
    logic [7:0] dice_array_sb_0_2_N_o;
    logic dice_array_sb_0_2_pred_N_o;
    logic [7:0] dice_array_sb_0_2_NE_o;
    logic dice_array_sb_0_2_pred_NE_o;
    logic [7:0] dice_array_sb_0_2_NW_o;
    logic dice_array_sb_0_2_pred_NW_o;
    logic [7:0] dice_array_sb_0_4_N_o;
    logic dice_array_sb_0_4_pred_N_o;
    logic [7:0] dice_array_sb_0_4_NE_o;
    logic dice_array_sb_0_4_pred_NE_o;
    logic [7:0] dice_array_sb_0_4_NW_o;
    logic dice_array_sb_0_4_pred_NW_o;
    logic [7:0] dice_array_sb_0_6_N_o;
    logic dice_array_sb_0_6_pred_N_o;
    logic [7:0] dice_array_sb_0_6_NE_o;
    logic dice_array_sb_0_6_pred_NE_o;
    logic [7:0] dice_array_sb_0_6_NW_o;
    logic dice_array_sb_0_6_pred_NW_o;
    logic [7:0] dice_array_sb_0_8_N_o;
    logic dice_array_sb_0_8_pred_N_o;
    logic [7:0] dice_array_sb_0_8_E_o;
    logic dice_array_sb_0_8_pred_E_o;
    logic [7:0] dice_array_sb_0_8_NE_o;
    logic dice_array_sb_0_8_pred_NE_o;
    logic [7:0] dice_array_sb_0_8_NW_o;
    logic dice_array_sb_0_8_pred_NW_o;
    logic [7:0] dice_array_sb_0_8_SE_o;
    logic dice_array_sb_0_8_pred_SE_o;
    logic [7:0] dice_array_sb_2_0_W_o;
    logic dice_array_sb_2_0_pred_W_o;
    logic [7:0] dice_array_sb_2_0_NW_o;
    logic dice_array_sb_2_0_pred_NW_o;
    logic [7:0] dice_array_sb_2_0_SW_o;
    logic dice_array_sb_2_0_pred_SW_o;
    logic [7:0] dice_array_sb_2_8_E_o;
    logic dice_array_sb_2_8_pred_E_o;
    logic [7:0] dice_array_sb_2_8_NE_o;
    logic dice_array_sb_2_8_pred_NE_o;
    logic [7:0] dice_array_sb_2_8_SE_o;
    logic dice_array_sb_2_8_pred_SE_o;
    logic [7:0] dice_array_sb_4_0_W_o;
    logic dice_array_sb_4_0_pred_W_o;
    logic [7:0] dice_array_sb_4_0_NW_o;
    logic dice_array_sb_4_0_pred_NW_o;
    logic [7:0] dice_array_sb_4_0_SW_o;
    logic dice_array_sb_4_0_pred_SW_o;
    logic [7:0] dice_array_sb_4_8_E_o;
    logic dice_array_sb_4_8_pred_E_o;
    logic [7:0] dice_array_sb_4_8_NE_o;
    logic dice_array_sb_4_8_pred_NE_o;
    logic [7:0] dice_array_sb_4_8_SE_o;
    logic dice_array_sb_4_8_pred_SE_o;
    logic [7:0] dice_array_sb_6_0_W_o;
    logic dice_array_sb_6_0_pred_W_o;
    logic [7:0] dice_array_sb_6_0_NW_o;
    logic dice_array_sb_6_0_pred_NW_o;
    logic [7:0] dice_array_sb_6_0_SW_o;
    logic dice_array_sb_6_0_pred_SW_o;
    logic [7:0] dice_array_sb_6_8_E_o;
    logic dice_array_sb_6_8_pred_E_o;
    logic [7:0] dice_array_sb_6_8_NE_o;
    logic dice_array_sb_6_8_pred_NE_o;
    logic [7:0] dice_array_sb_6_8_SE_o;
    logic dice_array_sb_6_8_pred_SE_o;
    logic [7:0] dice_array_sb_8_0_S_o;
    logic dice_array_sb_8_0_pred_S_o;
    logic [7:0] dice_array_sb_8_0_W_o;
    logic dice_array_sb_8_0_pred_W_o;
    logic [7:0] dice_array_sb_8_0_NW_o;
    logic dice_array_sb_8_0_pred_NW_o;
    logic [7:0] dice_array_sb_8_0_SE_o;
    logic dice_array_sb_8_0_pred_SE_o;
    logic [7:0] dice_array_sb_8_0_SW_o;
    logic dice_array_sb_8_0_pred_SW_o;
    logic [7:0] dice_array_sb_8_2_S_o;
    logic dice_array_sb_8_2_pred_S_o;
    logic [7:0] dice_array_sb_8_2_SE_o;
    logic dice_array_sb_8_2_pred_SE_o;
    logic [7:0] dice_array_sb_8_2_SW_o;
    logic dice_array_sb_8_2_pred_SW_o;
    logic [7:0] dice_array_sb_8_4_S_o;
    logic dice_array_sb_8_4_pred_S_o;
    logic [7:0] dice_array_sb_8_4_SE_o;
    logic dice_array_sb_8_4_pred_SE_o;
    logic [7:0] dice_array_sb_8_4_SW_o;
    logic dice_array_sb_8_4_pred_SW_o;
    logic [7:0] dice_array_sb_8_6_S_o;
    logic dice_array_sb_8_6_pred_S_o;
    logic [7:0] dice_array_sb_8_6_SE_o;
    logic dice_array_sb_8_6_pred_SE_o;
    logic [7:0] dice_array_sb_8_6_SW_o;
    logic dice_array_sb_8_6_pred_SW_o;
    logic [7:0] dice_array_sb_8_8_S_o;
    logic dice_array_sb_8_8_pred_S_o;
    logic [7:0] dice_array_sb_8_8_E_o;
    logic dice_array_sb_8_8_pred_E_o;
    logic [7:0] dice_array_sb_8_8_NE_o;
    logic dice_array_sb_8_8_pred_NE_o;
    logic [7:0] dice_array_sb_8_8_SE_o;
    logic dice_array_sb_8_8_pred_SE_o;
    logic [7:0] dice_array_sb_8_8_SW_o;
    logic dice_array_sb_8_8_pred_SW_o;
    logic dice_array_prog_dout_o;
    logic dice_array_prog_we_o;
    logic [7:0] xbar_data_in_inst_data_o_0;
    logic [7:0] xbar_data_in_inst_data_o_1;
    logic [7:0] xbar_data_in_inst_data_o_2;
    logic [7:0] xbar_data_in_inst_data_o_3;
    logic [7:0] xbar_data_in_inst_data_o_4;
    logic [7:0] xbar_data_in_inst_data_o_5;
    logic [7:0] xbar_data_in_inst_data_o_6;
    logic [7:0] xbar_data_in_inst_data_o_7;
    logic [7:0] xbar_data_in_inst_data_o_8;
    logic [7:0] xbar_data_in_inst_data_o_9;
    logic [7:0] xbar_data_out_inst_data_o_0;
    logic [7:0] xbar_data_out_inst_data_o_1;
    logic [7:0] xbar_data_out_inst_data_o_2;
    logic [7:0] xbar_data_out_inst_data_o_3;
    logic [7:0] xbar_data_out_inst_data_o_4;
    logic [7:0] xbar_data_out_inst_data_o_5;
    logic [7:0] xbar_data_out_inst_data_o_6;
    logic [7:0] xbar_data_out_inst_data_o_7;
    logic [7:0] xbar_data_out_inst_data_o_8;
    logic [7:0] xbar_data_out_inst_data_o_9;
    logic [7:0] xbar_data_out_inst_data_o_10;
    logic [7:0] xbar_data_out_inst_data_o_11;
    logic [7:0] xbar_data_out_inst_data_o_12;
    logic [7:0] xbar_data_out_inst_data_o_13;
    logic [7:0] xbar_data_out_inst_data_o_14;
    logic [7:0] xbar_data_out_inst_data_o_15;
    logic xbar_pred_in_inst_data_o_0;
    logic xbar_pred_in_inst_data_o_1;
    logic xbar_pred_in_inst_data_o_2;
    logic xbar_pred_in_inst_data_o_3;
    logic xbar_pred_in_inst_data_o_4;
    logic xbar_pred_in_inst_data_o_5;
    logic xbar_pred_in_inst_data_o_6;
    logic xbar_pred_in_inst_data_o_7;
    logic xbar_pred_in_inst_data_o_8;
    logic xbar_pred_in_inst_data_o_9;
    logic xbar_pred_out_inst_data_o_0;
    logic xbar_pred_out_inst_data_o_1;
    logic [7:0] xbar_mem_data_inst_data_o_0;
    logic [7:0] xbar_mem_addr_inst_data_o_0;
    logic [39:0] i_prog_data_xbar_data_in_inst_prog_data_o;
    logic i_prog_data_xbar_data_in_inst_prog_dout_o;
    logic [63:0] i_prog_data_xbar_data_out_inst_prog_data_o;
    logic i_prog_data_xbar_data_out_inst_prog_dout_o;
    logic [3:0] i_prog_data_xbar_mem_addr_inst_prog_data_o;
    logic i_prog_data_xbar_mem_addr_inst_prog_dout_o;
    logic [3:0] i_prog_data_xbar_mem_data_inst_prog_data_o;
    logic i_prog_data_xbar_mem_data_inst_prog_dout_o;
    logic [9:0] i_prog_data_xbar_pred_in_inst_prog_data_o;
    logic i_prog_data_xbar_pred_in_inst_prog_dout_o;
    logic [7:0] i_prog_data_xbar_pred_out_inst_prog_data_o;
    logic i_prog_data_xbar_pred_out_inst_prog_dout_o;

    // Unconnected Wires
    logic [7:0] unconnected_dice_array_sb_0_0_N_i;
    logic unconnected_dice_array_sb_0_0_pred_N_i;
    logic [7:0] unconnected_dice_array_sb_0_0_NE_i;
    logic unconnected_dice_array_sb_0_0_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_0_0_NW_i;
    logic unconnected_dice_array_sb_0_0_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_0_0_SW_i;
    logic unconnected_dice_array_sb_0_0_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_0_2_N_i;
    logic unconnected_dice_array_sb_0_2_pred_N_i;
    logic [7:0] unconnected_dice_array_sb_0_2_NE_i;
    logic unconnected_dice_array_sb_0_2_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_0_2_NW_i;
    logic unconnected_dice_array_sb_0_2_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_0_4_N_i;
    logic unconnected_dice_array_sb_0_4_pred_N_i;
    logic [7:0] unconnected_dice_array_sb_0_4_NE_i;
    logic unconnected_dice_array_sb_0_4_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_0_4_NW_i;
    logic unconnected_dice_array_sb_0_4_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_0_6_N_i;
    logic unconnected_dice_array_sb_0_6_pred_N_i;
    logic [7:0] unconnected_dice_array_sb_0_6_NE_i;
    logic unconnected_dice_array_sb_0_6_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_0_6_NW_i;
    logic unconnected_dice_array_sb_0_6_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_0_8_N_i;
    logic unconnected_dice_array_sb_0_8_pred_N_i;
    logic [7:0] unconnected_dice_array_sb_0_8_NE_i;
    logic unconnected_dice_array_sb_0_8_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_0_8_NW_i;
    logic unconnected_dice_array_sb_0_8_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_0_8_SE_i;
    logic unconnected_dice_array_sb_0_8_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_2_0_NW_i;
    logic unconnected_dice_array_sb_2_0_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_2_0_SW_i;
    logic unconnected_dice_array_sb_2_0_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_2_8_NE_i;
    logic unconnected_dice_array_sb_2_8_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_2_8_SE_i;
    logic unconnected_dice_array_sb_2_8_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_4_0_NW_i;
    logic unconnected_dice_array_sb_4_0_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_4_0_SW_i;
    logic unconnected_dice_array_sb_4_0_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_4_8_NE_i;
    logic unconnected_dice_array_sb_4_8_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_4_8_SE_i;
    logic unconnected_dice_array_sb_4_8_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_6_0_NW_i;
    logic unconnected_dice_array_sb_6_0_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_6_0_SW_i;
    logic unconnected_dice_array_sb_6_0_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_6_8_NE_i;
    logic unconnected_dice_array_sb_6_8_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_6_8_SE_i;
    logic unconnected_dice_array_sb_6_8_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_8_0_S_i;
    logic unconnected_dice_array_sb_8_0_pred_S_i;
    logic [7:0] unconnected_dice_array_sb_8_0_NW_i;
    logic unconnected_dice_array_sb_8_0_pred_NW_i;
    logic [7:0] unconnected_dice_array_sb_8_0_SE_i;
    logic unconnected_dice_array_sb_8_0_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_8_0_SW_i;
    logic unconnected_dice_array_sb_8_0_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_8_2_S_i;
    logic unconnected_dice_array_sb_8_2_pred_S_i;
    logic [7:0] unconnected_dice_array_sb_8_2_SE_i;
    logic unconnected_dice_array_sb_8_2_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_8_2_SW_i;
    logic unconnected_dice_array_sb_8_2_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_8_4_S_i;
    logic unconnected_dice_array_sb_8_4_pred_S_i;
    logic [7:0] unconnected_dice_array_sb_8_4_SE_i;
    logic unconnected_dice_array_sb_8_4_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_8_4_SW_i;
    logic unconnected_dice_array_sb_8_4_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_8_6_S_i;
    logic unconnected_dice_array_sb_8_6_pred_S_i;
    logic [7:0] unconnected_dice_array_sb_8_6_SE_i;
    logic unconnected_dice_array_sb_8_6_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_8_6_SW_i;
    logic unconnected_dice_array_sb_8_6_pred_SW_i;
    logic [7:0] unconnected_dice_array_sb_8_8_S_i;
    logic unconnected_dice_array_sb_8_8_pred_S_i;
    logic [7:0] unconnected_dice_array_sb_8_8_NE_i;
    logic unconnected_dice_array_sb_8_8_pred_NE_i;
    logic [7:0] unconnected_dice_array_sb_8_8_SE_i;
    logic unconnected_dice_array_sb_8_8_pred_SE_i;
    logic [7:0] unconnected_dice_array_sb_8_8_SW_i;
    logic unconnected_dice_array_sb_8_8_pred_SW_i;

    // Instances
    mini_dice dice_array (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .sb_0_0_N_i(unconnected_dice_array_sb_0_0_N_i),
        .sb_0_0_N_o(dice_array_sb_0_0_N_o),
        .sb_0_0_pred_N_i(unconnected_dice_array_sb_0_0_pred_N_i),
        .sb_0_0_pred_N_o(dice_array_sb_0_0_pred_N_o),
        .sb_0_0_W_i(xbar_data_in_inst_data_o_0),
        .sb_0_0_W_o(dice_array_sb_0_0_W_o),
        .sb_0_0_pred_W_i(xbar_pred_in_inst_data_o_0),
        .sb_0_0_pred_W_o(dice_array_sb_0_0_pred_W_o),
        .sb_0_0_NE_i(unconnected_dice_array_sb_0_0_NE_i),
        .sb_0_0_NE_o(dice_array_sb_0_0_NE_o),
        .sb_0_0_pred_NE_i(unconnected_dice_array_sb_0_0_pred_NE_i),
        .sb_0_0_pred_NE_o(dice_array_sb_0_0_pred_NE_o),
        .sb_0_0_NW_i(unconnected_dice_array_sb_0_0_NW_i),
        .sb_0_0_NW_o(dice_array_sb_0_0_NW_o),
        .sb_0_0_pred_NW_i(unconnected_dice_array_sb_0_0_pred_NW_i),
        .sb_0_0_pred_NW_o(dice_array_sb_0_0_pred_NW_o),
        .sb_0_0_SW_i(unconnected_dice_array_sb_0_0_SW_i),
        .sb_0_0_SW_o(dice_array_sb_0_0_SW_o),
        .sb_0_0_pred_SW_i(unconnected_dice_array_sb_0_0_pred_SW_i),
        .sb_0_0_pred_SW_o(dice_array_sb_0_0_pred_SW_o),
        .sb_0_2_N_i(unconnected_dice_array_sb_0_2_N_i),
        .sb_0_2_N_o(dice_array_sb_0_2_N_o),
        .sb_0_2_pred_N_i(unconnected_dice_array_sb_0_2_pred_N_i),
        .sb_0_2_pred_N_o(dice_array_sb_0_2_pred_N_o),
        .sb_0_2_NE_i(unconnected_dice_array_sb_0_2_NE_i),
        .sb_0_2_NE_o(dice_array_sb_0_2_NE_o),
        .sb_0_2_pred_NE_i(unconnected_dice_array_sb_0_2_pred_NE_i),
        .sb_0_2_pred_NE_o(dice_array_sb_0_2_pred_NE_o),
        .sb_0_2_NW_i(unconnected_dice_array_sb_0_2_NW_i),
        .sb_0_2_NW_o(dice_array_sb_0_2_NW_o),
        .sb_0_2_pred_NW_i(unconnected_dice_array_sb_0_2_pred_NW_i),
        .sb_0_2_pred_NW_o(dice_array_sb_0_2_pred_NW_o),
        .sb_0_4_N_i(unconnected_dice_array_sb_0_4_N_i),
        .sb_0_4_N_o(dice_array_sb_0_4_N_o),
        .sb_0_4_pred_N_i(unconnected_dice_array_sb_0_4_pred_N_i),
        .sb_0_4_pred_N_o(dice_array_sb_0_4_pred_N_o),
        .sb_0_4_NE_i(unconnected_dice_array_sb_0_4_NE_i),
        .sb_0_4_NE_o(dice_array_sb_0_4_NE_o),
        .sb_0_4_pred_NE_i(unconnected_dice_array_sb_0_4_pred_NE_i),
        .sb_0_4_pred_NE_o(dice_array_sb_0_4_pred_NE_o),
        .sb_0_4_NW_i(unconnected_dice_array_sb_0_4_NW_i),
        .sb_0_4_NW_o(dice_array_sb_0_4_NW_o),
        .sb_0_4_pred_NW_i(unconnected_dice_array_sb_0_4_pred_NW_i),
        .sb_0_4_pred_NW_o(dice_array_sb_0_4_pred_NW_o),
        .sb_0_6_N_i(unconnected_dice_array_sb_0_6_N_i),
        .sb_0_6_N_o(dice_array_sb_0_6_N_o),
        .sb_0_6_pred_N_i(unconnected_dice_array_sb_0_6_pred_N_i),
        .sb_0_6_pred_N_o(dice_array_sb_0_6_pred_N_o),
        .sb_0_6_NE_i(unconnected_dice_array_sb_0_6_NE_i),
        .sb_0_6_NE_o(dice_array_sb_0_6_NE_o),
        .sb_0_6_pred_NE_i(unconnected_dice_array_sb_0_6_pred_NE_i),
        .sb_0_6_pred_NE_o(dice_array_sb_0_6_pred_NE_o),
        .sb_0_6_NW_i(unconnected_dice_array_sb_0_6_NW_i),
        .sb_0_6_NW_o(dice_array_sb_0_6_NW_o),
        .sb_0_6_pred_NW_i(unconnected_dice_array_sb_0_6_pred_NW_i),
        .sb_0_6_pred_NW_o(dice_array_sb_0_6_pred_NW_o),
        .sb_0_8_N_i(unconnected_dice_array_sb_0_8_N_i),
        .sb_0_8_N_o(dice_array_sb_0_8_N_o),
        .sb_0_8_pred_N_i(unconnected_dice_array_sb_0_8_pred_N_i),
        .sb_0_8_pred_N_o(dice_array_sb_0_8_pred_N_o),
        .sb_0_8_E_i(xbar_data_in_inst_data_o_5),
        .sb_0_8_E_o(dice_array_sb_0_8_E_o),
        .sb_0_8_pred_E_i(xbar_pred_in_inst_data_o_5),
        .sb_0_8_pred_E_o(dice_array_sb_0_8_pred_E_o),
        .sb_0_8_NE_i(unconnected_dice_array_sb_0_8_NE_i),
        .sb_0_8_NE_o(dice_array_sb_0_8_NE_o),
        .sb_0_8_pred_NE_i(unconnected_dice_array_sb_0_8_pred_NE_i),
        .sb_0_8_pred_NE_o(dice_array_sb_0_8_pred_NE_o),
        .sb_0_8_NW_i(unconnected_dice_array_sb_0_8_NW_i),
        .sb_0_8_NW_o(dice_array_sb_0_8_NW_o),
        .sb_0_8_pred_NW_i(unconnected_dice_array_sb_0_8_pred_NW_i),
        .sb_0_8_pred_NW_o(dice_array_sb_0_8_pred_NW_o),
        .sb_0_8_SE_i(unconnected_dice_array_sb_0_8_SE_i),
        .sb_0_8_SE_o(dice_array_sb_0_8_SE_o),
        .sb_0_8_pred_SE_i(unconnected_dice_array_sb_0_8_pred_SE_i),
        .sb_0_8_pred_SE_o(dice_array_sb_0_8_pred_SE_o),
        .sb_2_0_W_i(xbar_data_in_inst_data_o_1),
        .sb_2_0_W_o(dice_array_sb_2_0_W_o),
        .sb_2_0_pred_W_i(xbar_pred_in_inst_data_o_1),
        .sb_2_0_pred_W_o(dice_array_sb_2_0_pred_W_o),
        .sb_2_0_NW_i(unconnected_dice_array_sb_2_0_NW_i),
        .sb_2_0_NW_o(dice_array_sb_2_0_NW_o),
        .sb_2_0_pred_NW_i(unconnected_dice_array_sb_2_0_pred_NW_i),
        .sb_2_0_pred_NW_o(dice_array_sb_2_0_pred_NW_o),
        .sb_2_0_SW_i(unconnected_dice_array_sb_2_0_SW_i),
        .sb_2_0_SW_o(dice_array_sb_2_0_SW_o),
        .sb_2_0_pred_SW_i(unconnected_dice_array_sb_2_0_pred_SW_i),
        .sb_2_0_pred_SW_o(dice_array_sb_2_0_pred_SW_o),
        .sb_2_8_E_i(xbar_data_in_inst_data_o_6),
        .sb_2_8_E_o(dice_array_sb_2_8_E_o),
        .sb_2_8_pred_E_i(xbar_pred_in_inst_data_o_6),
        .sb_2_8_pred_E_o(dice_array_sb_2_8_pred_E_o),
        .sb_2_8_NE_i(unconnected_dice_array_sb_2_8_NE_i),
        .sb_2_8_NE_o(dice_array_sb_2_8_NE_o),
        .sb_2_8_pred_NE_i(unconnected_dice_array_sb_2_8_pred_NE_i),
        .sb_2_8_pred_NE_o(dice_array_sb_2_8_pred_NE_o),
        .sb_2_8_SE_i(unconnected_dice_array_sb_2_8_SE_i),
        .sb_2_8_SE_o(dice_array_sb_2_8_SE_o),
        .sb_2_8_pred_SE_i(unconnected_dice_array_sb_2_8_pred_SE_i),
        .sb_2_8_pred_SE_o(dice_array_sb_2_8_pred_SE_o),
        .sb_4_0_W_i(xbar_data_in_inst_data_o_2),
        .sb_4_0_W_o(dice_array_sb_4_0_W_o),
        .sb_4_0_pred_W_i(xbar_pred_in_inst_data_o_2),
        .sb_4_0_pred_W_o(dice_array_sb_4_0_pred_W_o),
        .sb_4_0_NW_i(unconnected_dice_array_sb_4_0_NW_i),
        .sb_4_0_NW_o(dice_array_sb_4_0_NW_o),
        .sb_4_0_pred_NW_i(unconnected_dice_array_sb_4_0_pred_NW_i),
        .sb_4_0_pred_NW_o(dice_array_sb_4_0_pred_NW_o),
        .sb_4_0_SW_i(unconnected_dice_array_sb_4_0_SW_i),
        .sb_4_0_SW_o(dice_array_sb_4_0_SW_o),
        .sb_4_0_pred_SW_i(unconnected_dice_array_sb_4_0_pred_SW_i),
        .sb_4_0_pred_SW_o(dice_array_sb_4_0_pred_SW_o),
        .sb_4_8_E_i(xbar_data_in_inst_data_o_7),
        .sb_4_8_E_o(dice_array_sb_4_8_E_o),
        .sb_4_8_pred_E_i(xbar_pred_in_inst_data_o_7),
        .sb_4_8_pred_E_o(dice_array_sb_4_8_pred_E_o),
        .sb_4_8_NE_i(unconnected_dice_array_sb_4_8_NE_i),
        .sb_4_8_NE_o(dice_array_sb_4_8_NE_o),
        .sb_4_8_pred_NE_i(unconnected_dice_array_sb_4_8_pred_NE_i),
        .sb_4_8_pred_NE_o(dice_array_sb_4_8_pred_NE_o),
        .sb_4_8_SE_i(unconnected_dice_array_sb_4_8_SE_i),
        .sb_4_8_SE_o(dice_array_sb_4_8_SE_o),
        .sb_4_8_pred_SE_i(unconnected_dice_array_sb_4_8_pred_SE_i),
        .sb_4_8_pred_SE_o(dice_array_sb_4_8_pred_SE_o),
        .sb_6_0_W_i(xbar_data_in_inst_data_o_3),
        .sb_6_0_W_o(dice_array_sb_6_0_W_o),
        .sb_6_0_pred_W_i(xbar_pred_in_inst_data_o_3),
        .sb_6_0_pred_W_o(dice_array_sb_6_0_pred_W_o),
        .sb_6_0_NW_i(unconnected_dice_array_sb_6_0_NW_i),
        .sb_6_0_NW_o(dice_array_sb_6_0_NW_o),
        .sb_6_0_pred_NW_i(unconnected_dice_array_sb_6_0_pred_NW_i),
        .sb_6_0_pred_NW_o(dice_array_sb_6_0_pred_NW_o),
        .sb_6_0_SW_i(unconnected_dice_array_sb_6_0_SW_i),
        .sb_6_0_SW_o(dice_array_sb_6_0_SW_o),
        .sb_6_0_pred_SW_i(unconnected_dice_array_sb_6_0_pred_SW_i),
        .sb_6_0_pred_SW_o(dice_array_sb_6_0_pred_SW_o),
        .sb_6_8_E_i(xbar_data_in_inst_data_o_8),
        .sb_6_8_E_o(dice_array_sb_6_8_E_o),
        .sb_6_8_pred_E_i(xbar_pred_in_inst_data_o_8),
        .sb_6_8_pred_E_o(dice_array_sb_6_8_pred_E_o),
        .sb_6_8_NE_i(unconnected_dice_array_sb_6_8_NE_i),
        .sb_6_8_NE_o(dice_array_sb_6_8_NE_o),
        .sb_6_8_pred_NE_i(unconnected_dice_array_sb_6_8_pred_NE_i),
        .sb_6_8_pred_NE_o(dice_array_sb_6_8_pred_NE_o),
        .sb_6_8_SE_i(unconnected_dice_array_sb_6_8_SE_i),
        .sb_6_8_SE_o(dice_array_sb_6_8_SE_o),
        .sb_6_8_pred_SE_i(unconnected_dice_array_sb_6_8_pred_SE_i),
        .sb_6_8_pred_SE_o(dice_array_sb_6_8_pred_SE_o),
        .sb_8_0_S_i(unconnected_dice_array_sb_8_0_S_i),
        .sb_8_0_S_o(dice_array_sb_8_0_S_o),
        .sb_8_0_pred_S_i(unconnected_dice_array_sb_8_0_pred_S_i),
        .sb_8_0_pred_S_o(dice_array_sb_8_0_pred_S_o),
        .sb_8_0_W_i(xbar_data_in_inst_data_o_4),
        .sb_8_0_W_o(dice_array_sb_8_0_W_o),
        .sb_8_0_pred_W_i(xbar_pred_in_inst_data_o_4),
        .sb_8_0_pred_W_o(dice_array_sb_8_0_pred_W_o),
        .sb_8_0_NW_i(unconnected_dice_array_sb_8_0_NW_i),
        .sb_8_0_NW_o(dice_array_sb_8_0_NW_o),
        .sb_8_0_pred_NW_i(unconnected_dice_array_sb_8_0_pred_NW_i),
        .sb_8_0_pred_NW_o(dice_array_sb_8_0_pred_NW_o),
        .sb_8_0_SE_i(unconnected_dice_array_sb_8_0_SE_i),
        .sb_8_0_SE_o(dice_array_sb_8_0_SE_o),
        .sb_8_0_pred_SE_i(unconnected_dice_array_sb_8_0_pred_SE_i),
        .sb_8_0_pred_SE_o(dice_array_sb_8_0_pred_SE_o),
        .sb_8_0_SW_i(unconnected_dice_array_sb_8_0_SW_i),
        .sb_8_0_SW_o(dice_array_sb_8_0_SW_o),
        .sb_8_0_pred_SW_i(unconnected_dice_array_sb_8_0_pred_SW_i),
        .sb_8_0_pred_SW_o(dice_array_sb_8_0_pred_SW_o),
        .sb_8_2_S_i(unconnected_dice_array_sb_8_2_S_i),
        .sb_8_2_S_o(dice_array_sb_8_2_S_o),
        .sb_8_2_pred_S_i(unconnected_dice_array_sb_8_2_pred_S_i),
        .sb_8_2_pred_S_o(dice_array_sb_8_2_pred_S_o),
        .sb_8_2_SE_i(unconnected_dice_array_sb_8_2_SE_i),
        .sb_8_2_SE_o(dice_array_sb_8_2_SE_o),
        .sb_8_2_pred_SE_i(unconnected_dice_array_sb_8_2_pred_SE_i),
        .sb_8_2_pred_SE_o(dice_array_sb_8_2_pred_SE_o),
        .sb_8_2_SW_i(unconnected_dice_array_sb_8_2_SW_i),
        .sb_8_2_SW_o(dice_array_sb_8_2_SW_o),
        .sb_8_2_pred_SW_i(unconnected_dice_array_sb_8_2_pred_SW_i),
        .sb_8_2_pred_SW_o(dice_array_sb_8_2_pred_SW_o),
        .sb_8_4_S_i(unconnected_dice_array_sb_8_4_S_i),
        .sb_8_4_S_o(dice_array_sb_8_4_S_o),
        .sb_8_4_pred_S_i(unconnected_dice_array_sb_8_4_pred_S_i),
        .sb_8_4_pred_S_o(dice_array_sb_8_4_pred_S_o),
        .sb_8_4_SE_i(unconnected_dice_array_sb_8_4_SE_i),
        .sb_8_4_SE_o(dice_array_sb_8_4_SE_o),
        .sb_8_4_pred_SE_i(unconnected_dice_array_sb_8_4_pred_SE_i),
        .sb_8_4_pred_SE_o(dice_array_sb_8_4_pred_SE_o),
        .sb_8_4_SW_i(unconnected_dice_array_sb_8_4_SW_i),
        .sb_8_4_SW_o(dice_array_sb_8_4_SW_o),
        .sb_8_4_pred_SW_i(unconnected_dice_array_sb_8_4_pred_SW_i),
        .sb_8_4_pred_SW_o(dice_array_sb_8_4_pred_SW_o),
        .sb_8_6_S_i(unconnected_dice_array_sb_8_6_S_i),
        .sb_8_6_S_o(dice_array_sb_8_6_S_o),
        .sb_8_6_pred_S_i(unconnected_dice_array_sb_8_6_pred_S_i),
        .sb_8_6_pred_S_o(dice_array_sb_8_6_pred_S_o),
        .sb_8_6_SE_i(unconnected_dice_array_sb_8_6_SE_i),
        .sb_8_6_SE_o(dice_array_sb_8_6_SE_o),
        .sb_8_6_pred_SE_i(unconnected_dice_array_sb_8_6_pred_SE_i),
        .sb_8_6_pred_SE_o(dice_array_sb_8_6_pred_SE_o),
        .sb_8_6_SW_i(unconnected_dice_array_sb_8_6_SW_i),
        .sb_8_6_SW_o(dice_array_sb_8_6_SW_o),
        .sb_8_6_pred_SW_i(unconnected_dice_array_sb_8_6_pred_SW_i),
        .sb_8_6_pred_SW_o(dice_array_sb_8_6_pred_SW_o),
        .sb_8_8_S_i(unconnected_dice_array_sb_8_8_S_i),
        .sb_8_8_S_o(dice_array_sb_8_8_S_o),
        .sb_8_8_pred_S_i(unconnected_dice_array_sb_8_8_pred_S_i),
        .sb_8_8_pred_S_o(dice_array_sb_8_8_pred_S_o),
        .sb_8_8_E_i(xbar_data_in_inst_data_o_9),
        .sb_8_8_E_o(dice_array_sb_8_8_E_o),
        .sb_8_8_pred_E_i(xbar_pred_in_inst_data_o_9),
        .sb_8_8_pred_E_o(dice_array_sb_8_8_pred_E_o),
        .sb_8_8_NE_i(unconnected_dice_array_sb_8_8_NE_i),
        .sb_8_8_NE_o(dice_array_sb_8_8_NE_o),
        .sb_8_8_pred_NE_i(unconnected_dice_array_sb_8_8_pred_NE_i),
        .sb_8_8_pred_NE_o(dice_array_sb_8_8_pred_NE_o),
        .sb_8_8_SE_i(unconnected_dice_array_sb_8_8_SE_i),
        .sb_8_8_SE_o(dice_array_sb_8_8_SE_o),
        .sb_8_8_pred_SE_i(unconnected_dice_array_sb_8_8_pred_SE_i),
        .sb_8_8_pred_SE_o(dice_array_sb_8_8_pred_SE_o),
        .sb_8_8_SW_i(unconnected_dice_array_sb_8_8_SW_i),
        .sb_8_8_SW_o(dice_array_sb_8_8_SW_o),
        .sb_8_8_pred_SW_i(unconnected_dice_array_sb_8_8_pred_SW_i),
        .sb_8_8_pred_SW_o(dice_array_sb_8_8_pred_SW_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(prog_we_i),
        .prog_din_i(prog_din_i),
        .prog_dout_o(dice_array_prog_dout_o),
        .prog_we_o(dice_array_prog_we_o)
    );

    xbar_data_in xbar_data_in_inst (
        .data_i_0(ext_data_i_0),
        .data_i_1(ext_data_i_1),
        .data_i_2(ext_data_i_2),
        .data_i_3(ext_data_i_3),
        .data_i_4(ext_data_i_4),
        .data_i_5(ext_data_i_5),
        .data_i_6(ext_data_i_6),
        .data_i_7(ext_data_i_7),
        .data_i_8(ext_data_i_8),
        .data_i_9(ext_data_i_9),
        .data_i_10(ext_data_i_10),
        .data_i_11(ext_data_i_11),
        .data_i_12(ext_data_i_12),
        .data_i_13(ext_data_i_13),
        .data_i_14(ext_data_i_14),
        .data_i_15(ext_data_i_15),
        .data_o_0(xbar_data_in_inst_data_o_0),
        .data_o_1(xbar_data_in_inst_data_o_1),
        .data_o_2(xbar_data_in_inst_data_o_2),
        .data_o_3(xbar_data_in_inst_data_o_3),
        .data_o_4(xbar_data_in_inst_data_o_4),
        .data_o_5(xbar_data_in_inst_data_o_5),
        .data_o_6(xbar_data_in_inst_data_o_6),
        .data_o_7(xbar_data_in_inst_data_o_7),
        .data_o_8(xbar_data_in_inst_data_o_8),
        .data_o_9(xbar_data_in_inst_data_o_9),
        .prog_data_i(i_prog_data_xbar_data_in_inst_prog_data_o),
        .prog_done_i(prog_done_i)
    );

    xbar_data_out xbar_data_out_inst (
        .data_i_0(dice_array_sb_0_0_W_o),
        .data_i_1(dice_array_sb_2_0_W_o),
        .data_i_2(dice_array_sb_4_0_W_o),
        .data_i_3(dice_array_sb_6_0_W_o),
        .data_i_4(dice_array_sb_8_0_W_o),
        .data_i_5(dice_array_sb_0_8_E_o),
        .data_i_6(dice_array_sb_2_8_E_o),
        .data_i_7(dice_array_sb_4_8_E_o),
        .data_i_8(dice_array_sb_6_8_E_o),
        .data_i_9(dice_array_sb_8_8_E_o),
        .data_o_0(xbar_data_out_inst_data_o_0),
        .data_o_1(xbar_data_out_inst_data_o_1),
        .data_o_2(xbar_data_out_inst_data_o_2),
        .data_o_3(xbar_data_out_inst_data_o_3),
        .data_o_4(xbar_data_out_inst_data_o_4),
        .data_o_5(xbar_data_out_inst_data_o_5),
        .data_o_6(xbar_data_out_inst_data_o_6),
        .data_o_7(xbar_data_out_inst_data_o_7),
        .data_o_8(xbar_data_out_inst_data_o_8),
        .data_o_9(xbar_data_out_inst_data_o_9),
        .data_o_10(xbar_data_out_inst_data_o_10),
        .data_o_11(xbar_data_out_inst_data_o_11),
        .data_o_12(xbar_data_out_inst_data_o_12),
        .data_o_13(xbar_data_out_inst_data_o_13),
        .data_o_14(xbar_data_out_inst_data_o_14),
        .data_o_15(xbar_data_out_inst_data_o_15),
        .prog_data_i(i_prog_data_xbar_data_out_inst_prog_data_o),
        .prog_done_i(prog_done_i)
    );

    xbar_pred_in xbar_pred_in_inst (
        .data_i_0(ext_pred_i_0),
        .data_i_1(ext_pred_i_1),
        .data_o_0(xbar_pred_in_inst_data_o_0),
        .data_o_1(xbar_pred_in_inst_data_o_1),
        .data_o_2(xbar_pred_in_inst_data_o_2),
        .data_o_3(xbar_pred_in_inst_data_o_3),
        .data_o_4(xbar_pred_in_inst_data_o_4),
        .data_o_5(xbar_pred_in_inst_data_o_5),
        .data_o_6(xbar_pred_in_inst_data_o_6),
        .data_o_7(xbar_pred_in_inst_data_o_7),
        .data_o_8(xbar_pred_in_inst_data_o_8),
        .data_o_9(xbar_pred_in_inst_data_o_9),
        .prog_data_i(i_prog_data_xbar_pred_in_inst_prog_data_o),
        .prog_done_i(prog_done_i)
    );

    xbar_pred_out xbar_pred_out_inst (
        .data_i_0(dice_array_sb_0_0_pred_W_o),
        .data_i_1(dice_array_sb_2_0_pred_W_o),
        .data_i_2(dice_array_sb_4_0_pred_W_o),
        .data_i_3(dice_array_sb_6_0_pred_W_o),
        .data_i_4(dice_array_sb_8_0_pred_W_o),
        .data_i_5(dice_array_sb_0_8_pred_E_o),
        .data_i_6(dice_array_sb_2_8_pred_E_o),
        .data_i_7(dice_array_sb_4_8_pred_E_o),
        .data_i_8(dice_array_sb_6_8_pred_E_o),
        .data_i_9(dice_array_sb_8_8_pred_E_o),
        .data_o_0(xbar_pred_out_inst_data_o_0),
        .data_o_1(xbar_pred_out_inst_data_o_1),
        .prog_data_i(i_prog_data_xbar_pred_out_inst_prog_data_o),
        .prog_done_i(prog_done_i)
    );

    xbar_mem_data xbar_mem_data_inst (
        .data_i_0(dice_array_sb_0_0_N_o),
        .data_i_1(dice_array_sb_0_2_N_o),
        .data_i_2(dice_array_sb_0_4_N_o),
        .data_i_3(dice_array_sb_0_6_N_o),
        .data_i_4(dice_array_sb_0_8_N_o),
        .data_i_5(dice_array_sb_8_0_S_o),
        .data_i_6(dice_array_sb_8_2_S_o),
        .data_i_7(dice_array_sb_8_4_S_o),
        .data_i_8(dice_array_sb_8_6_S_o),
        .data_i_9(dice_array_sb_8_8_S_o),
        .data_o_0(xbar_mem_data_inst_data_o_0),
        .prog_data_i(i_prog_data_xbar_mem_data_inst_prog_data_o),
        .prog_done_i(prog_done_i)
    );

    xbar_mem_addr xbar_mem_addr_inst (
        .data_i_0(dice_array_sb_0_0_N_o),
        .data_i_1(dice_array_sb_0_2_N_o),
        .data_i_2(dice_array_sb_0_4_N_o),
        .data_i_3(dice_array_sb_0_6_N_o),
        .data_i_4(dice_array_sb_0_8_N_o),
        .data_i_5(dice_array_sb_8_0_S_o),
        .data_i_6(dice_array_sb_8_2_S_o),
        .data_i_7(dice_array_sb_8_4_S_o),
        .data_i_8(dice_array_sb_8_6_S_o),
        .data_i_9(dice_array_sb_8_8_S_o),
        .data_o_0(xbar_mem_addr_inst_data_o_0),
        .prog_data_i(i_prog_data_xbar_mem_addr_inst_prog_data_o),
        .prog_done_i(prog_done_i)
    );

    scanchain_data_d40_contexts_1 i_prog_data_xbar_data_in_inst (
        .prog_data_o(i_prog_data_xbar_data_in_inst_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(dice_array_prog_we_o),
        .prog_din_i(dice_array_prog_dout_o),
        .prog_dout_o(i_prog_data_xbar_data_in_inst_prog_dout_o)
    );

    scanchain_data_d64_contexts_1 i_prog_data_xbar_data_out_inst (
        .prog_data_o(i_prog_data_xbar_data_out_inst_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(dice_array_prog_we_o),
        .prog_din_i(i_prog_data_xbar_data_in_inst_prog_dout_o),
        .prog_dout_o(i_prog_data_xbar_data_out_inst_prog_dout_o)
    );

    scanchain_data_d4_contexts_1 i_prog_data_xbar_mem_addr_inst (
        .prog_data_o(i_prog_data_xbar_mem_addr_inst_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(dice_array_prog_we_o),
        .prog_din_i(i_prog_data_xbar_data_out_inst_prog_dout_o),
        .prog_dout_o(i_prog_data_xbar_mem_addr_inst_prog_dout_o)
    );

    scanchain_data_d4_contexts_1 i_prog_data_xbar_mem_data_inst (
        .prog_data_o(i_prog_data_xbar_mem_data_inst_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(dice_array_prog_we_o),
        .prog_din_i(i_prog_data_xbar_mem_addr_inst_prog_dout_o),
        .prog_dout_o(i_prog_data_xbar_mem_data_inst_prog_dout_o)
    );

    scanchain_data_d10_contexts_1 i_prog_data_xbar_pred_in_inst (
        .prog_data_o(i_prog_data_xbar_pred_in_inst_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(dice_array_prog_we_o),
        .prog_din_i(i_prog_data_xbar_mem_data_inst_prog_dout_o),
        .prog_dout_o(i_prog_data_xbar_pred_in_inst_prog_dout_o)
    );

    scanchain_data_d8_contexts_1 i_prog_data_xbar_pred_out_inst (
        .prog_data_o(i_prog_data_xbar_pred_out_inst_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(dice_array_prog_we_o),
        .prog_din_i(i_prog_data_xbar_pred_in_inst_prog_dout_o),
        .prog_dout_o(i_prog_data_xbar_pred_out_inst_prog_dout_o)
    );

    // Output Port Connections
    assign ext_data_o_0 = xbar_data_out_inst_data_o_0;
    assign ext_data_o_1 = xbar_data_out_inst_data_o_1;
    assign ext_data_o_2 = xbar_data_out_inst_data_o_2;
    assign ext_data_o_3 = xbar_data_out_inst_data_o_3;
    assign ext_data_o_4 = xbar_data_out_inst_data_o_4;
    assign ext_data_o_5 = xbar_data_out_inst_data_o_5;
    assign ext_data_o_6 = xbar_data_out_inst_data_o_6;
    assign ext_data_o_7 = xbar_data_out_inst_data_o_7;
    assign ext_data_o_8 = xbar_data_out_inst_data_o_8;
    assign ext_data_o_9 = xbar_data_out_inst_data_o_9;
    assign ext_data_o_10 = xbar_data_out_inst_data_o_10;
    assign ext_data_o_11 = xbar_data_out_inst_data_o_11;
    assign ext_data_o_12 = xbar_data_out_inst_data_o_12;
    assign ext_data_o_13 = xbar_data_out_inst_data_o_13;
    assign ext_data_o_14 = xbar_data_out_inst_data_o_14;
    assign ext_data_o_15 = xbar_data_out_inst_data_o_15;
    assign ext_pred_o_0 = xbar_pred_out_inst_data_o_0;
    assign ext_pred_o_1 = xbar_pred_out_inst_data_o_1;
    assign mem_data_o = xbar_mem_data_inst_data_o_0;
    assign mem_addr_o = xbar_mem_addr_inst_data_o_0;
    assign prog_dout_o = i_prog_data_xbar_pred_out_inst_prog_dout_o;
    assign prog_we_o = dice_array_prog_we_o;
endmodule
