// SystemVerilog auto-generated by DORA RTL generator
// Copyright (c) 2025, Pᴺ Computer Engineering Lab.

// Generated on: 2026-03-04 19:22:21.843409
// Author: patrick

module pe (
    // Ports
    input  logic clk_i,
    input  logic reset_i,
    input  logic en_i,
    input  logic [7:0] pe_NE_i,
    input  logic [7:0] pe_NW_i,
    input  logic [7:0] pe_SE_i,
    input  logic [7:0] pe_SW_i,
    output logic [7:0] pe_NE_o,
    output logic [7:0] pe_NW_o,
    output logic [7:0] pe_SE_o,
    output logic [7:0] pe_SW_o,
    input  logic pe_pred_NE_i,
    input  logic pe_pred_NW_i,
    input  logic pe_pred_SE_i,
    input  logic pe_pred_SW_i,
    output logic pe_pred_NE_o,
    output logic pe_pred_NW_o,
    output logic pe_pred_SE_o,
    output logic pe_pred_SW_o,
    input  logic prog_clk_i,
    input  logic prog_rst_i,
    input  logic prog_done_i,
    input  logic prog_we_i,
    input  logic prog_din_i,
    output logic prog_dout_o,
    output logic prog_we_o
);
    logic [7:0] alu_inst_out;
    logic [7:0] reg_8b_inst_data_o;
    logic [7:0] phi_mux_inst_data_o;
    logic pred_nonzero_inst_pred_o;
    logic pred_reg_inst_data_o;
    logic [7:0] i_sw_alu_inst_A_out_o;
    logic [7:0] i_sw_alu_inst_B_out_o;
    logic [7:0] i_sw_pe_NE_o_out_o;
    logic [7:0] i_sw_pe_NW_o_out_o;
    logic [7:0] i_sw_pe_SE_o_out_o;
    logic [7:0] i_sw_pe_SW_o_out_o;
    logic i_sw_phi_mux_inst_pred_i_out_o;
    logic [7:0] i_sw_phi_mux_inst_data_true_i_out_o;
    logic [7:0] i_sw_phi_mux_inst_data_false_i_out_o;
    logic i_buf_prog_rst_l0_data_o;
    logic i_buf_prog_done_l0_data_o;
    logic i_scanchain_head_prog_we_o;
    logic i_scanchain_head_prog_dout_o;
    logic [1:0] i_prog_data_alu_inst_prog_data_o;
    logic i_prog_data_alu_inst_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_alu_inst_A_prog_data_o;
    logic i_prog_data_i_sw_alu_inst_A_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_alu_inst_B_prog_data_o;
    logic i_prog_data_i_sw_alu_inst_B_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_pe_NE_o_prog_data_o;
    logic i_prog_data_i_sw_pe_NE_o_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_pe_NW_o_prog_data_o;
    logic i_prog_data_i_sw_pe_NW_o_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_pe_SE_o_prog_data_o;
    logic i_prog_data_i_sw_pe_SE_o_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_pe_SW_o_prog_data_o;
    logic i_prog_data_i_sw_pe_SW_o_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_phi_mux_inst_data_false_i_prog_data_o;
    logic i_prog_data_i_sw_phi_mux_inst_data_false_i_prog_dout_o;
    logic [1:0] i_prog_data_i_sw_phi_mux_inst_data_true_i_prog_data_o;
    logic i_prog_data_i_sw_phi_mux_inst_data_true_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_phi_mux_inst_pred_i_prog_data_o;
    logic i_prog_data_i_sw_phi_mux_inst_pred_i_prog_dout_o;
    logic i_scanchain_tail_prog_we_o;
    logic i_scanchain_tail_prog_dout_o;

    // Unconnected Wires

    // Instances
    fu_int8_add_int8_sub_int8_mul alu_inst (
        .A(i_sw_alu_inst_A_out_o),
        .B(i_sw_alu_inst_B_out_o),
        .out(alu_inst_out),
        .clk_i(clk_i),
        .prog_data_i(i_prog_data_alu_inst_prog_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o)
    );

    reg_8b reg_8b_inst (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(alu_inst_out),
        .data_o(reg_8b_inst_data_o)
    );

    phi_mux_8b phi_mux_inst (
        .pred_i(i_sw_phi_mux_inst_pred_i_out_o),
        .data_true_i(i_sw_phi_mux_inst_data_true_i_out_o),
        .data_false_i(i_sw_phi_mux_inst_data_false_i_out_o),
        .data_o(phi_mux_inst_data_o)
    );

    pred_nonzero_8b pred_nonzero_inst (
        .data_i(alu_inst_out),
        .pred_o(pred_nonzero_inst_pred_o)
    );

    reg_1b pred_reg_inst (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_nonzero_inst_pred_o),
        .data_o(pred_reg_inst_data_o)
    );

    sw_4_8b i_sw_alu_inst_A (
        .i_0(pe_NE_i),
        .i_1(pe_NW_i),
        .i_2(pe_SE_i),
        .i_3(pe_SW_i),
        .out_o(i_sw_alu_inst_A_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_alu_inst_A_prog_data_o)
    );

    sw_4_8b i_sw_alu_inst_B (
        .i_0(pe_NE_i),
        .i_1(pe_NW_i),
        .i_2(pe_SE_i),
        .i_3(pe_SW_i),
        .out_o(i_sw_alu_inst_B_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_alu_inst_B_prog_data_o)
    );

    sw_3_8b i_sw_pe_NE_o (
        .i_0(reg_8b_inst_data_o),
        .i_1(alu_inst_out),
        .i_2(phi_mux_inst_data_o),
        .out_o(i_sw_pe_NE_o_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_pe_NE_o_prog_data_o)
    );

    sw_3_8b i_sw_pe_NW_o (
        .i_0(reg_8b_inst_data_o),
        .i_1(alu_inst_out),
        .i_2(phi_mux_inst_data_o),
        .out_o(i_sw_pe_NW_o_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_pe_NW_o_prog_data_o)
    );

    sw_3_8b i_sw_pe_SE_o (
        .i_0(reg_8b_inst_data_o),
        .i_1(alu_inst_out),
        .i_2(phi_mux_inst_data_o),
        .out_o(i_sw_pe_SE_o_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_pe_SE_o_prog_data_o)
    );

    sw_3_8b i_sw_pe_SW_o (
        .i_0(reg_8b_inst_data_o),
        .i_1(alu_inst_out),
        .i_2(phi_mux_inst_data_o),
        .out_o(i_sw_pe_SW_o_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_pe_SW_o_prog_data_o)
    );

    sw_5_1b i_sw_phi_mux_inst_pred_i (
        .i_0(pred_reg_inst_data_o),
        .i_1(pe_pred_NE_i),
        .i_2(pe_pred_NW_i),
        .i_3(pe_pred_SE_i),
        .i_4(pe_pred_SW_i),
        .out_o(i_sw_phi_mux_inst_pred_i_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_phi_mux_inst_pred_i_prog_data_o)
    );

    sw_3_8b i_sw_phi_mux_inst_data_true_i (
        .i_0(pe_NW_i),
        .i_1(pe_NE_i),
        .i_2(alu_inst_out),
        .out_o(i_sw_phi_mux_inst_data_true_i_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_phi_mux_inst_data_true_i_prog_data_o)
    );

    sw_3_8b i_sw_phi_mux_inst_data_false_i (
        .i_0(pe_SE_i),
        .i_1(pe_SW_i),
        .i_2(reg_8b_inst_data_o),
        .out_o(i_sw_phi_mux_inst_data_false_i_out_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_data_i(i_prog_data_i_sw_phi_mux_inst_data_false_i_prog_data_o)
    );

    simple_buf i_buf_prog_rst_l0 (
        .clk_i(prog_clk_i),
        .data_i(prog_rst_i),
        .data_o(i_buf_prog_rst_l0_data_o)
    );

    simple_bufr i_buf_prog_done_l0 (
        .clk_i(prog_clk_i),
        .reset_i(i_buf_prog_rst_l0_data_o),
        .data_i(prog_done_i),
        .data_o(i_buf_prog_done_l0_data_o)
    );

    scanchain_delim i_scanchain_head (
        .prog_we_o(i_scanchain_head_prog_we_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(prog_we_i),
        .prog_din_i(prog_din_i),
        .prog_dout_o(i_scanchain_head_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_alu_inst (
        .prog_data_o(i_prog_data_alu_inst_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_scanchain_head_prog_dout_o),
        .prog_dout_o(i_prog_data_alu_inst_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_alu_inst_A (
        .prog_data_o(i_prog_data_i_sw_alu_inst_A_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_alu_inst_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_alu_inst_A_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_alu_inst_B (
        .prog_data_o(i_prog_data_i_sw_alu_inst_B_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_alu_inst_A_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_alu_inst_B_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_pe_NE_o (
        .prog_data_o(i_prog_data_i_sw_pe_NE_o_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_alu_inst_B_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pe_NE_o_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_pe_NW_o (
        .prog_data_o(i_prog_data_i_sw_pe_NW_o_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pe_NE_o_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pe_NW_o_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_pe_SE_o (
        .prog_data_o(i_prog_data_i_sw_pe_SE_o_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pe_NW_o_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pe_SE_o_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_pe_SW_o (
        .prog_data_o(i_prog_data_i_sw_pe_SW_o_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pe_SE_o_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pe_SW_o_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_phi_mux_inst_data_false_i (
        .prog_data_o(i_prog_data_i_sw_phi_mux_inst_data_false_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pe_SW_o_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_phi_mux_inst_data_false_i_prog_dout_o)
    );

    scanchain_data_d2_contexts_1 i_prog_data_i_sw_phi_mux_inst_data_true_i (
        .prog_data_o(i_prog_data_i_sw_phi_mux_inst_data_true_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_phi_mux_inst_data_false_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_phi_mux_inst_data_true_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_phi_mux_inst_pred_i (
        .prog_data_o(i_prog_data_i_sw_phi_mux_inst_pred_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_phi_mux_inst_data_true_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_phi_mux_inst_pred_i_prog_dout_o)
    );

    scanchain_delim i_scanchain_tail (
        .prog_we_o(i_scanchain_tail_prog_we_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(i_buf_prog_rst_l0_data_o),
        .prog_done_i(i_buf_prog_done_l0_data_o),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_phi_mux_inst_pred_i_prog_dout_o),
        .prog_dout_o(i_scanchain_tail_prog_dout_o)
    );

    // Output Port Connections
    assign pe_NE_o = i_sw_pe_NE_o_out_o;
    assign pe_NW_o = i_sw_pe_NW_o_out_o;
    assign pe_SE_o = i_sw_pe_SE_o_out_o;
    assign pe_SW_o = i_sw_pe_SW_o_out_o;
    assign pe_pred_NE_o = pred_nonzero_inst_pred_o;
    assign pe_pred_NW_o = pred_nonzero_inst_pred_o;
    assign pe_pred_SE_o = pred_nonzero_inst_pred_o;
    assign pe_pred_SW_o = pred_nonzero_inst_pred_o;
    assign prog_dout_o = i_scanchain_tail_prog_dout_o;
    assign prog_we_o = i_scanchain_tail_prog_we_o;
endmodule
