// SystemVerilog auto-generated by DORA RTL generator
// Copyright (c) 2025, Pᴺ Computer Engineering Lab.

// Generated on: 2026-03-16 13:48:55.562724
// Author: jami3jun

module sb (
    // Ports
    input  logic clk_i,
    input  logic reset_i,
    input  logic en_i,
    input  logic [7:0] sb_N_i,
    input  logic [7:0] sb_E_i,
    input  logic [7:0] sb_W_i,
    input  logic [7:0] sb_S_i,
    output logic [7:0] sb_N_o,
    output logic [7:0] sb_E_o,
    output logic [7:0] sb_W_o,
    output logic [7:0] sb_S_o,
    input  logic [7:0] sb_NE_i,
    input  logic [7:0] sb_NW_i,
    input  logic [7:0] sb_SE_i,
    input  logic [7:0] sb_SW_i,
    output logic [7:0] sb_NE_o,
    output logic [7:0] sb_NW_o,
    output logic [7:0] sb_SE_o,
    output logic [7:0] sb_SW_o,
    input  logic sb_pred_N_i,
    input  logic sb_pred_E_i,
    input  logic sb_pred_W_i,
    input  logic sb_pred_S_i,
    input  logic sb_pred_NE_i,
    input  logic sb_pred_NW_i,
    input  logic sb_pred_SE_i,
    input  logic sb_pred_SW_i,
    output logic sb_pred_N_o,
    output logic sb_pred_E_o,
    output logic sb_pred_W_o,
    output logic sb_pred_S_o,
    output logic sb_pred_NE_o,
    output logic sb_pred_NW_o,
    output logic sb_pred_SE_o,
    output logic sb_pred_SW_o,
    input  logic prog_clk_i,
    input  logic prog_rst_i,
    input  logic prog_done_i,
    input  logic prog_we_i,
    input  logic prog_din_i,
    output logic prog_dout_o,
    output logic prog_we_o
);
    logic [7:0] out_reg_N_data_o;
    logic [7:0] out_reg_E_data_o;
    logic [7:0] out_reg_W_data_o;
    logic [7:0] out_reg_S_data_o;
    logic [7:0] out_reg_NE_data_o;
    logic [7:0] out_reg_NW_data_o;
    logic [7:0] out_reg_SE_data_o;
    logic [7:0] out_reg_SW_data_o;
    logic [7:0] xbar_tap_N_data_o;
    logic [7:0] xbar_tap_E_data_o;
    logic [7:0] xbar_tap_W_data_o;
    logic [7:0] xbar_tap_S_data_o;
    logic [7:0] xbar_tap_NE_data_o;
    logic [7:0] xbar_tap_NW_data_o;
    logic [7:0] xbar_tap_SE_data_o;
    logic [7:0] xbar_tap_SW_data_o;
    logic pred_xbar_tap_N_data_o;
    logic pred_out_reg_N_data_o;
    logic pred_xbar_tap_E_data_o;
    logic pred_out_reg_E_data_o;
    logic pred_xbar_tap_W_data_o;
    logic pred_out_reg_W_data_o;
    logic pred_xbar_tap_S_data_o;
    logic pred_out_reg_S_data_o;
    logic pred_xbar_tap_NE_data_o;
    logic pred_out_reg_NE_data_o;
    logic pred_xbar_tap_NW_data_o;
    logic pred_out_reg_NW_data_o;
    logic pred_xbar_tap_SE_data_o;
    logic pred_out_reg_SE_data_o;
    logic pred_xbar_tap_SW_data_o;
    logic pred_out_reg_SW_data_o;
    logic [7:0] i_sw_xbar_tap_N_data_i_out_o;
    logic [7:0] i_sw_xbar_tap_E_data_i_out_o;
    logic [7:0] i_sw_xbar_tap_W_data_i_out_o;
    logic [7:0] i_sw_xbar_tap_S_data_i_out_o;
    logic [7:0] i_sw_xbar_tap_NE_data_i_out_o;
    logic [7:0] i_sw_xbar_tap_NW_data_i_out_o;
    logic [7:0] i_sw_xbar_tap_SE_data_i_out_o;
    logic [7:0] i_sw_xbar_tap_SW_data_i_out_o;
    logic i_sw_pred_xbar_tap_N_data_i_out_o;
    logic i_sw_pred_xbar_tap_E_data_i_out_o;
    logic i_sw_pred_xbar_tap_W_data_i_out_o;
    logic i_sw_pred_xbar_tap_S_data_i_out_o;
    logic i_sw_pred_xbar_tap_NE_data_i_out_o;
    logic i_sw_pred_xbar_tap_NW_data_i_out_o;
    logic i_sw_pred_xbar_tap_SE_data_i_out_o;
    logic i_sw_pred_xbar_tap_SW_data_i_out_o;
    logic i_scanchain_head_prog_we_o;
    logic i_scanchain_head_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_E_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_E_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_NE_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_NE_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_NW_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_NW_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_N_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_N_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_SE_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_SE_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_SW_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_SW_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_S_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_S_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_pred_xbar_tap_W_data_i_prog_data_o;
    logic i_prog_data_i_sw_pred_xbar_tap_W_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_E_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_E_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_NE_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_NE_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_NW_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_NW_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_N_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_N_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_SE_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_SE_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_SW_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_SW_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_S_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_S_data_i_prog_dout_o;
    logic [2:0] i_prog_data_i_sw_xbar_tap_W_data_i_prog_data_o;
    logic i_prog_data_i_sw_xbar_tap_W_data_i_prog_dout_o;
    logic i_scanchain_tail_prog_we_o;
    logic i_scanchain_tail_prog_dout_o;

    // Unconnected Wires

    // Instances
    reg_8b out_reg_N (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_N_data_o),
        .data_o(out_reg_N_data_o)
    );

    reg_8b out_reg_E (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_E_data_o),
        .data_o(out_reg_E_data_o)
    );

    reg_8b out_reg_W (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_W_data_o),
        .data_o(out_reg_W_data_o)
    );

    reg_8b out_reg_S (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_S_data_o),
        .data_o(out_reg_S_data_o)
    );

    reg_8b out_reg_NE (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_NE_data_o),
        .data_o(out_reg_NE_data_o)
    );

    reg_8b out_reg_NW (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_NW_data_o),
        .data_o(out_reg_NW_data_o)
    );

    reg_8b out_reg_SE (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_SE_data_o),
        .data_o(out_reg_SE_data_o)
    );

    reg_8b out_reg_SW (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(xbar_tap_SW_data_o),
        .data_o(out_reg_SW_data_o)
    );

    sb_xbar_tap_8b xbar_tap_N (
        .data_i(i_sw_xbar_tap_N_data_i_out_o),
        .data_o(xbar_tap_N_data_o)
    );

    sb_xbar_tap_8b xbar_tap_E (
        .data_i(i_sw_xbar_tap_E_data_i_out_o),
        .data_o(xbar_tap_E_data_o)
    );

    sb_xbar_tap_8b xbar_tap_W (
        .data_i(i_sw_xbar_tap_W_data_i_out_o),
        .data_o(xbar_tap_W_data_o)
    );

    sb_xbar_tap_8b xbar_tap_S (
        .data_i(i_sw_xbar_tap_S_data_i_out_o),
        .data_o(xbar_tap_S_data_o)
    );

    sb_xbar_tap_8b xbar_tap_NE (
        .data_i(i_sw_xbar_tap_NE_data_i_out_o),
        .data_o(xbar_tap_NE_data_o)
    );

    sb_xbar_tap_8b xbar_tap_NW (
        .data_i(i_sw_xbar_tap_NW_data_i_out_o),
        .data_o(xbar_tap_NW_data_o)
    );

    sb_xbar_tap_8b xbar_tap_SE (
        .data_i(i_sw_xbar_tap_SE_data_i_out_o),
        .data_o(xbar_tap_SE_data_o)
    );

    sb_xbar_tap_8b xbar_tap_SW (
        .data_i(i_sw_xbar_tap_SW_data_i_out_o),
        .data_o(xbar_tap_SW_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_N (
        .data_i(i_sw_pred_xbar_tap_N_data_i_out_o),
        .data_o(pred_xbar_tap_N_data_o)
    );

    reg_1b pred_out_reg_N (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_N_data_o),
        .data_o(pred_out_reg_N_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_E (
        .data_i(i_sw_pred_xbar_tap_E_data_i_out_o),
        .data_o(pred_xbar_tap_E_data_o)
    );

    reg_1b pred_out_reg_E (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_E_data_o),
        .data_o(pred_out_reg_E_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_W (
        .data_i(i_sw_pred_xbar_tap_W_data_i_out_o),
        .data_o(pred_xbar_tap_W_data_o)
    );

    reg_1b pred_out_reg_W (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_W_data_o),
        .data_o(pred_out_reg_W_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_S (
        .data_i(i_sw_pred_xbar_tap_S_data_i_out_o),
        .data_o(pred_xbar_tap_S_data_o)
    );

    reg_1b pred_out_reg_S (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_S_data_o),
        .data_o(pred_out_reg_S_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_NE (
        .data_i(i_sw_pred_xbar_tap_NE_data_i_out_o),
        .data_o(pred_xbar_tap_NE_data_o)
    );

    reg_1b pred_out_reg_NE (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_NE_data_o),
        .data_o(pred_out_reg_NE_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_NW (
        .data_i(i_sw_pred_xbar_tap_NW_data_i_out_o),
        .data_o(pred_xbar_tap_NW_data_o)
    );

    reg_1b pred_out_reg_NW (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_NW_data_o),
        .data_o(pred_out_reg_NW_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_SE (
        .data_i(i_sw_pred_xbar_tap_SE_data_i_out_o),
        .data_o(pred_xbar_tap_SE_data_o)
    );

    reg_1b pred_out_reg_SE (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_SE_data_o),
        .data_o(pred_out_reg_SE_data_o)
    );

    sb_xbar_tap_1b pred_xbar_tap_SW (
        .data_i(i_sw_pred_xbar_tap_SW_data_i_out_o),
        .data_o(pred_xbar_tap_SW_data_o)
    );

    reg_1b pred_out_reg_SW (
        .clk_i(clk_i),
        .reset_i(reset_i),
        .en_i(en_i),
        .data_i(pred_xbar_tap_SW_data_o),
        .data_o(pred_out_reg_SW_data_o)
    );

    sw_8_8b i_sw_xbar_tap_N_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_N_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_N_data_i_prog_data_o)
    );

    sw_8_8b i_sw_xbar_tap_E_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_E_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_E_data_i_prog_data_o)
    );

    sw_8_8b i_sw_xbar_tap_W_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_W_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_W_data_i_prog_data_o)
    );

    sw_8_8b i_sw_xbar_tap_S_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_S_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_S_data_i_prog_data_o)
    );

    sw_8_8b i_sw_xbar_tap_NE_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_NE_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_NE_data_i_prog_data_o)
    );

    sw_8_8b i_sw_xbar_tap_NW_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_NW_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_NW_data_i_prog_data_o)
    );

    sw_8_8b i_sw_xbar_tap_SE_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_SE_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_SE_data_i_prog_data_o)
    );

    sw_8_8b i_sw_xbar_tap_SW_data_i (
        .i_0(sb_N_i),
        .i_1(sb_E_i),
        .i_2(sb_W_i),
        .i_3(sb_S_i),
        .i_4(sb_NE_i),
        .i_5(sb_NW_i),
        .i_6(sb_SE_i),
        .i_7(sb_SW_i),
        .out_o(i_sw_xbar_tap_SW_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_xbar_tap_SW_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_N_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_N_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_N_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_E_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_E_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_E_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_W_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_W_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_W_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_S_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_S_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_S_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_NE_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_NE_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_NE_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_NW_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_NW_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_NW_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_SE_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_SE_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_SE_data_i_prog_data_o)
    );

    sw_8_1b i_sw_pred_xbar_tap_SW_data_i (
        .i_0(sb_pred_N_i),
        .i_1(sb_pred_E_i),
        .i_2(sb_pred_W_i),
        .i_3(sb_pred_S_i),
        .i_4(sb_pred_NE_i),
        .i_5(sb_pred_NW_i),
        .i_6(sb_pred_SE_i),
        .i_7(sb_pred_SW_i),
        .out_o(i_sw_pred_xbar_tap_SW_data_i_out_o),
        .prog_done_i(prog_done_i),
        .prog_data_i(i_prog_data_i_sw_pred_xbar_tap_SW_data_i_prog_data_o)
    );

    scanchain_delim i_scanchain_head (
        .prog_we_o(i_scanchain_head_prog_we_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(prog_we_i),
        .prog_din_i(prog_din_i),
        .prog_dout_o(i_scanchain_head_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_E_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_E_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_scanchain_head_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_E_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_NE_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_NE_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_E_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_NE_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_NW_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_NW_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_NE_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_NW_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_N_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_N_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_NW_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_N_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_SE_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_SE_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_N_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_SE_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_SW_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_SW_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_SE_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_SW_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_S_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_S_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_SW_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_S_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_pred_xbar_tap_W_data_i (
        .prog_data_o(i_prog_data_i_sw_pred_xbar_tap_W_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_S_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_pred_xbar_tap_W_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_E_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_E_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_pred_xbar_tap_W_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_E_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_NE_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_NE_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_E_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_NE_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_NW_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_NW_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_NE_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_NW_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_N_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_N_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_NW_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_N_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_SE_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_SE_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_N_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_SE_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_SW_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_SW_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_SE_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_SW_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_S_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_S_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_SW_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_S_data_i_prog_dout_o)
    );

    scanchain_data_d3_contexts_1 i_prog_data_i_sw_xbar_tap_W_data_i (
        .prog_data_o(i_prog_data_i_sw_xbar_tap_W_data_i_prog_data_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_S_data_i_prog_dout_o),
        .prog_dout_o(i_prog_data_i_sw_xbar_tap_W_data_i_prog_dout_o)
    );

    scanchain_delim i_scanchain_tail (
        .prog_we_o(i_scanchain_tail_prog_we_o),
        .prog_clk_i(prog_clk_i),
        .prog_rst_i(prog_rst_i),
        .prog_done_i(prog_done_i),
        .prog_we_i(i_scanchain_head_prog_we_o),
        .prog_din_i(i_prog_data_i_sw_xbar_tap_W_data_i_prog_dout_o),
        .prog_dout_o(i_scanchain_tail_prog_dout_o)
    );

    // Output Port Connections
    assign sb_N_o = out_reg_N_data_o;
    assign sb_E_o = out_reg_E_data_o;
    assign sb_W_o = out_reg_W_data_o;
    assign sb_S_o = out_reg_S_data_o;
    assign sb_NE_o = out_reg_NE_data_o;
    assign sb_NW_o = out_reg_NW_data_o;
    assign sb_SE_o = out_reg_SE_data_o;
    assign sb_SW_o = out_reg_SW_data_o;
    assign sb_pred_N_o = pred_out_reg_N_data_o;
    assign sb_pred_E_o = pred_out_reg_E_data_o;
    assign sb_pred_W_o = pred_out_reg_W_data_o;
    assign sb_pred_S_o = pred_out_reg_S_data_o;
    assign sb_pred_NE_o = pred_out_reg_NE_data_o;
    assign sb_pred_NW_o = pred_out_reg_NW_data_o;
    assign sb_pred_SE_o = pred_out_reg_SE_data_o;
    assign sb_pred_SW_o = pred_out_reg_SW_data_o;
    assign prog_dout_o = i_scanchain_tail_prog_dout_o;
    assign prog_we_o = i_scanchain_tail_prog_we_o;
endmodule
