// Automatically generated by DORA's RTL generator
`timescale 1ns/1ps
`include "bsg_defines.sv"

module scanchain_data_d64_contexts_1 #(
    parameter int chain_bitcount_p = 64,
    parameter int chain_width_p    = 1
)(
    input  logic                  prog_clk_i,
    input  logic                  prog_rst_i,
    input  logic                  prog_done_i,

    input  logic                  prog_we_i,
    input  logic [chain_width_p-1:0] prog_din_i,

    output logic [chain_bitcount_p-1:0] prog_data_o,
    output logic [chain_width_p-1:0]    prog_dout_o
);

    // Concatenate existing data and new input bits
    logic [chain_bitcount_p + chain_width_p - 1:0] prog_data_next;
    logic [chain_bitcount_p-1:0] prog_data_n;

    assign prog_data_next = {prog_data_o, prog_din_i};

    assign prog_data_n = (!prog_done_i && prog_we_i)
                         ? prog_data_next[0 +: chain_bitcount_p]
                         : prog_data_o;

    // NOTE: Async reset is intentional for the programming domain.
    // The scanchain must be resettable when prog_clk_i is not running.
    bsg_dff_async_reset #(.width_p(chain_bitcount_p)
                          ,.reset_val_p(0)
                          ) prog_data_reg
      (.clk_i(prog_clk_i)
       ,.async_reset_i(prog_rst_i)
       ,.data_i(prog_data_n)
       ,.data_o(prog_data_o)
       );

    // Output the shifted-out bits
    assign prog_dout_o = prog_data_next[chain_bitcount_p +: chain_width_p];

endmodule