// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
`include "bsg_defines.sv"

module scanchain_delim #(
    parameter int data_width_p = 1
)(
    input  logic             prog_clk_i,
    input  logic             prog_rst_i,
    input  logic             prog_done_i,

    input  logic             prog_we_i,
    input  logic [data_width_p-1:0] prog_din_i,

    output logic             prog_we_o,
    output logic [data_width_p-1:0] prog_dout_o
);

    logic [data_width_p:0] prog_payload_n;
    logic [data_width_p:0] prog_payload_r;

    assign prog_payload_n = (!prog_done_i && prog_we_i)
                            ? {1'b1, prog_din_i}
                            : {1'b0, prog_payload_r[data_width_p-1:0]};

    // NOTE: Async reset is intentional for the programming domain.
    // The scanchain must be resettable when prog_clk_i is not running.
    bsg_dff_async_reset #(.width_p(data_width_p+1)
                          ,.reset_val_p(0)
                          ) prog_delim_reg
      (.clk_i(prog_clk_i)
       ,.async_reset_i(prog_rst_i)
       ,.data_i(prog_payload_n)
       ,.data_o(prog_payload_r)
       );

    assign prog_we_o = prog_payload_r[data_width_p];
    assign prog_dout_o = prog_payload_r[data_width_p-1:0];

endmodule