// Automatically generated by DORA's RTL generator
`timescale 1ns/1ps

module simple_buf (
    input  logic clk_i   // clock
    ,input  logic data_i  // data in
    ,output logic data_o  // registered data out
);

    // Sequential (flip-flop) behavior
    always_ff @(posedge clk_i) begin
        data_o <= data_i;
    end

endmodule