// Automatically generated by DORA's RTL generator
`timescale 1ns/1ps

module simple_bufr (
    input  logic clk_i     // clock
    ,input  logic reset_i   // reset (active-high)
    ,input  logic data_i    // data input
    ,output logic data_o    // registered output
);

    // Sequential logic: D flip-flop with synchronous reset
    always_ff @(posedge clk_i) begin
        if (reset_i)
            data_o <= 1'b0;
        else
            data_o <= data_i;
    end

endmodule