// Automatically generated by DORA's RTL generator
`timescale 1ns/1ps

module sw_3_8b #(
    parameter int width_p      = 8
    ,parameter int sel_width_p  = 2
    ,parameter int num_inputs_p = 3
)(
    input  logic [width_p-1:0] i_0
    ,
    input  logic [width_p-1:0] i_1
    ,
    input  logic [width_p-1:0] i_2
    ,
    input  logic             prog_done_i
    ,input  logic [sel_width_p-1:0] prog_data_i
    ,output logic [width_p-1:0] out_o
);

    always_comb begin
        if (!prog_done_i) begin
            out_o = '0;
        end else begin
            unique case (prog_data_i)
                2'd0: out_o = i_0;
                2'd1: out_o = i_1;
                2'd2: out_o = i_2;
                default: out_o = '0;
            endcase
        end
    end

endmodule