// Automatically generated by DORA's RTL generator
`timescale 1ns/1ps

module sw_5_1b #(
    parameter int width_p      = 1
    ,parameter int sel_width_p  = 3
    ,parameter int num_inputs_p = 5
)(
    input  logic [width_p-1:0] i_0
    ,
    input  logic [width_p-1:0] i_1
    ,
    input  logic [width_p-1:0] i_2
    ,
    input  logic [width_p-1:0] i_3
    ,
    input  logic [width_p-1:0] i_4
    ,
    input  logic             prog_done_i
    ,input  logic [sel_width_p-1:0] prog_data_i
    ,output logic [width_p-1:0] out_o
);

    always_comb begin
        if (!prog_done_i) begin
            out_o = '0;
        end else begin
            unique case (prog_data_i)
                3'd0: out_o = i_0;
                3'd1: out_o = i_1;
                3'd2: out_o = i_2;
                3'd3: out_o = i_3;
                3'd4: out_o = i_4;
                default: out_o = '0;
            endcase
        end
    end

endmodule