// Automatically generated by DORA's RTL generator
// Scanchain-programmable crossbar adapted from cgra_crossbar.sv
// Dora & Claude (AI-generated)`timescale 1ns/1ps

module xbar_pred_in #(
    parameter int num_inputs_p  = 2
    ,parameter int num_outputs_p = 10
    ,parameter int data_width_p  = 1
    ,parameter int sel_width_lp  = 1
)(
    input  logic                                       prog_done_i
    ,input  logic [num_outputs_p*sel_width_lp-1:0]     prog_data_i
    ,input  logic [data_width_p-1:0] data_i_0
    ,input  logic [data_width_p-1:0] data_i_1
    ,output logic [data_width_p-1:0] data_o_0
    ,output logic [data_width_p-1:0] data_o_1
    ,output logic [data_width_p-1:0] data_o_2
    ,output logic [data_width_p-1:0] data_o_3
    ,output logic [data_width_p-1:0] data_o_4
    ,output logic [data_width_p-1:0] data_o_5
    ,output logic [data_width_p-1:0] data_o_6
    ,output logic [data_width_p-1:0] data_o_7
    ,output logic [data_width_p-1:0] data_o_8
    ,output logic [data_width_p-1:0] data_o_9
);

    always_comb begin
        if (!prog_done_i) begin
            data_o_0 = '0;
        end else begin
            unique case (prog_data_i[0*sel_width_lp +: sel_width_lp])
                1'd0: data_o_0 = data_i_0;
                1'd1: data_o_0 = data_i_1;
                default: data_o_0 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_1 = '0;
        end else begin
            unique case (prog_data_i[1*sel_width_lp +: sel_width_lp])
                1'd0: data_o_1 = data_i_0;
                1'd1: data_o_1 = data_i_1;
                default: data_o_1 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_2 = '0;
        end else begin
            unique case (prog_data_i[2*sel_width_lp +: sel_width_lp])
                1'd0: data_o_2 = data_i_0;
                1'd1: data_o_2 = data_i_1;
                default: data_o_2 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_3 = '0;
        end else begin
            unique case (prog_data_i[3*sel_width_lp +: sel_width_lp])
                1'd0: data_o_3 = data_i_0;
                1'd1: data_o_3 = data_i_1;
                default: data_o_3 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_4 = '0;
        end else begin
            unique case (prog_data_i[4*sel_width_lp +: sel_width_lp])
                1'd0: data_o_4 = data_i_0;
                1'd1: data_o_4 = data_i_1;
                default: data_o_4 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_5 = '0;
        end else begin
            unique case (prog_data_i[5*sel_width_lp +: sel_width_lp])
                1'd0: data_o_5 = data_i_0;
                1'd1: data_o_5 = data_i_1;
                default: data_o_5 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_6 = '0;
        end else begin
            unique case (prog_data_i[6*sel_width_lp +: sel_width_lp])
                1'd0: data_o_6 = data_i_0;
                1'd1: data_o_6 = data_i_1;
                default: data_o_6 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_7 = '0;
        end else begin
            unique case (prog_data_i[7*sel_width_lp +: sel_width_lp])
                1'd0: data_o_7 = data_i_0;
                1'd1: data_o_7 = data_i_1;
                default: data_o_7 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_8 = '0;
        end else begin
            unique case (prog_data_i[8*sel_width_lp +: sel_width_lp])
                1'd0: data_o_8 = data_i_0;
                1'd1: data_o_8 = data_i_1;
                default: data_o_8 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_9 = '0;
        end else begin
            unique case (prog_data_i[9*sel_width_lp +: sel_width_lp])
                1'd0: data_o_9 = data_i_0;
                1'd1: data_o_9 = data_i_1;
                default: data_o_9 = '0;
            endcase
        end
    end

endmodule