// Automatically generated by DORA's RTL generator
// Scanchain-programmable crossbar adapted from cgra_crossbar.sv
// Dora & Claude (AI-generated)`timescale 1ns/1ps

module xbar_pred_out #(
    parameter int num_inputs_p  = 10
    ,parameter int num_outputs_p = 2
    ,parameter int data_width_p  = 1
    ,parameter int sel_width_lp  = 4
)(
    input  logic                                       prog_done_i
    ,input  logic [num_outputs_p*sel_width_lp-1:0]     prog_data_i
    ,input  logic [data_width_p-1:0] data_i_0
    ,input  logic [data_width_p-1:0] data_i_1
    ,input  logic [data_width_p-1:0] data_i_2
    ,input  logic [data_width_p-1:0] data_i_3
    ,input  logic [data_width_p-1:0] data_i_4
    ,input  logic [data_width_p-1:0] data_i_5
    ,input  logic [data_width_p-1:0] data_i_6
    ,input  logic [data_width_p-1:0] data_i_7
    ,input  logic [data_width_p-1:0] data_i_8
    ,input  logic [data_width_p-1:0] data_i_9
    ,output logic [data_width_p-1:0] data_o_0
    ,output logic [data_width_p-1:0] data_o_1
);

    always_comb begin
        if (!prog_done_i) begin
            data_o_0 = '0;
        end else begin
            unique case (prog_data_i[0*sel_width_lp +: sel_width_lp])
                4'd0: data_o_0 = data_i_0;
                4'd1: data_o_0 = data_i_1;
                4'd2: data_o_0 = data_i_2;
                4'd3: data_o_0 = data_i_3;
                4'd4: data_o_0 = data_i_4;
                4'd5: data_o_0 = data_i_5;
                4'd6: data_o_0 = data_i_6;
                4'd7: data_o_0 = data_i_7;
                4'd8: data_o_0 = data_i_8;
                4'd9: data_o_0 = data_i_9;
                default: data_o_0 = '0;
            endcase
        end
    end

    always_comb begin
        if (!prog_done_i) begin
            data_o_1 = '0;
        end else begin
            unique case (prog_data_i[1*sel_width_lp +: sel_width_lp])
                4'd0: data_o_1 = data_i_0;
                4'd1: data_o_1 = data_i_1;
                4'd2: data_o_1 = data_i_2;
                4'd3: data_o_1 = data_i_3;
                4'd4: data_o_1 = data_i_4;
                4'd5: data_o_1 = data_i_5;
                4'd6: data_o_1 = data_i_6;
                4'd7: data_o_1 = data_i_7;
                4'd8: data_o_1 = data_i_8;
                4'd9: data_o_1 = data_i_9;
                default: data_o_1 = '0;
            endcase
        end
    end

endmodule