// Add-array test on the 32-thread cgra-nopred design.
//
// Identical pipeline to full_mul_array_test (load_a → load_b → COMPUTE →
// compute_store_addrs → store), except eblock 2 is `add_array.bin` instead
// of `mul_array.bin`. Verifies the CGRA's ALU ADD opcode path and the xbar
// routing for an add kernel — coverage that the multiply test cannot hit
// because every PE in `mul_array.bin` is configured with op=MUL.
//
// All wiring (mfetch addrs, bsfetch addrs, CSRs, AXI-Lite read_mem, thread
// count, dispatch) is inherited from the parent. Only the eblock-2 bitstream
// and the 128 expected store values differ — both come from
// test_data_add_array.svh, generated by gen_test_data.py against
// add_array_test_vector.json with stages= ..., add_array, ...
class dice_core_add_array_test extends dice_core_full_mul_array_test;
  `uvm_component_utils(dice_core_add_array_test)

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  // Replace the canonical mul setup with the add variant.
  virtual function void setup_thread_inputs_and_expectations();
    `include "test_data_add_array.svh"
  endfunction

endclass
